//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SizeID { get; set; }
        public string Sizes { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
