//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderMarket.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/isAuthenticationValid", ReplyAction="http://tempuri.org/IUserService/isAuthenticationValidResponse")]
        bool isAuthenticationValid(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/isAuthenticationValid", ReplyAction="http://tempuri.org/IUserService/isAuthenticationValidResponse")]
        System.Threading.Tasks.Task<bool> isAuthenticationValidAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        void AddUser(string username, string password, string email, string name, string surname, long contactno, bool buyer, bool seller);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(string username, string password, string email, string name, string surname, long contactno, bool buyer, bool seller);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DoesUsernameExist", ReplyAction="http://tempuri.org/IUserService/DoesUsernameExistResponse")]
        bool DoesUsernameExist(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DoesUsernameExist", ReplyAction="http://tempuri.org/IUserService/DoesUsernameExistResponse")]
        System.Threading.Tasks.Task<bool> DoesUsernameExistAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DoesEmailExist", ReplyAction="http://tempuri.org/IUserService/DoesEmailExistResponse")]
        bool DoesEmailExist(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DoesEmailExist", ReplyAction="http://tempuri.org/IUserService/DoesEmailExistResponse")]
        System.Threading.Tasks.Task<bool> DoesEmailExistAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        Commonlayer.User GetUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        System.Threading.Tasks.Task<Commonlayer.User> GetUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        Commonlayer.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<Commonlayer.User[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        void UpdateUser(string username, string email, string name, string surname, long contactno, bool buyer, bool seller);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(string username, string email, string name, string surname, long contactno, bool buyer, bool seller);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPublicKey", ReplyAction="http://tempuri.org/IUserService/GetPublicKeyResponse")]
        string GetPublicKey(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPublicKey", ReplyAction="http://tempuri.org/IUserService/GetPublicKeyResponse")]
        System.Threading.Tasks.Task<string> GetPublicKeyAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetCreditCards", ReplyAction="http://tempuri.org/IUserService/GetCreditCardsResponse")]
        Commonlayer.Views.CreditCardView[] GetCreditCards(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetCreditCards", ReplyAction="http://tempuri.org/IUserService/GetCreditCardsResponse")]
        System.Threading.Tasks.Task<Commonlayer.Views.CreditCardView[]> GetCreditCardsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserRoles", ReplyAction="http://tempuri.org/IUserService/GetUserRolesResponse")]
        Commonlayer.Role[] GetUserRoles(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserRoles", ReplyAction="http://tempuri.org/IUserService/GetUserRolesResponse")]
        System.Threading.Tasks.Task<Commonlayer.Role[]> GetUserRolesAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserRolesV", ReplyAction="http://tempuri.org/IUserService/GetUserRolesVResponse")]
        Commonlayer.Views.RolesView[] GetUserRolesV(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserRolesV", ReplyAction="http://tempuri.org/IUserService/GetUserRolesVResponse")]
        System.Threading.Tasks.Task<Commonlayer.Views.RolesView[]> GetUserRolesVAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddCreditCard", ReplyAction="http://tempuri.org/IUserService/AddCreditCardResponse")]
        void AddCreditCard(string email, string creditcardt, string cvv, string holder, decimal number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddCreditCard", ReplyAction="http://tempuri.org/IUserService/AddCreditCardResponse")]
        System.Threading.Tasks.Task AddCreditCardAsync(string email, string creditcardt, string cvv, string holder, decimal number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPrivateKey", ReplyAction="http://tempuri.org/IUserService/GetPrivateKeyResponse")]
        string GetPrivateKey(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetPrivateKey", ReplyAction="http://tempuri.org/IUserService/GetPrivateKeyResponse")]
        System.Threading.Tasks.Task<string> GetPrivateKeyAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : TraderMarket.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<TraderMarket.UserService.IUserService>, TraderMarket.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isAuthenticationValid(string email, string password) {
            return base.Channel.isAuthenticationValid(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> isAuthenticationValidAsync(string email, string password) {
            return base.Channel.isAuthenticationValidAsync(email, password);
        }
        
        public void AddUser(string username, string password, string email, string name, string surname, long contactno, bool buyer, bool seller) {
            base.Channel.AddUser(username, password, email, name, surname, contactno, buyer, seller);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(string username, string password, string email, string name, string surname, long contactno, bool buyer, bool seller) {
            return base.Channel.AddUserAsync(username, password, email, name, surname, contactno, buyer, seller);
        }
        
        public bool DoesUsernameExist(string username) {
            return base.Channel.DoesUsernameExist(username);
        }
        
        public System.Threading.Tasks.Task<bool> DoesUsernameExistAsync(string username) {
            return base.Channel.DoesUsernameExistAsync(username);
        }
        
        public bool DoesEmailExist(string email) {
            return base.Channel.DoesEmailExist(email);
        }
        
        public System.Threading.Tasks.Task<bool> DoesEmailExistAsync(string email) {
            return base.Channel.DoesEmailExistAsync(email);
        }
        
        public Commonlayer.User GetUser(string email) {
            return base.Channel.GetUser(email);
        }
        
        public System.Threading.Tasks.Task<Commonlayer.User> GetUserAsync(string email) {
            return base.Channel.GetUserAsync(email);
        }
        
        public Commonlayer.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<Commonlayer.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public void UpdateUser(string username, string email, string name, string surname, long contactno, bool buyer, bool seller) {
            base.Channel.UpdateUser(username, email, name, surname, contactno, buyer, seller);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(string username, string email, string name, string surname, long contactno, bool buyer, bool seller) {
            return base.Channel.UpdateUserAsync(username, email, name, surname, contactno, buyer, seller);
        }
        
        public string GetPublicKey(string email) {
            return base.Channel.GetPublicKey(email);
        }
        
        public System.Threading.Tasks.Task<string> GetPublicKeyAsync(string email) {
            return base.Channel.GetPublicKeyAsync(email);
        }
        
        public Commonlayer.Views.CreditCardView[] GetCreditCards(string email) {
            return base.Channel.GetCreditCards(email);
        }
        
        public System.Threading.Tasks.Task<Commonlayer.Views.CreditCardView[]> GetCreditCardsAsync(string email) {
            return base.Channel.GetCreditCardsAsync(email);
        }
        
        public Commonlayer.Role[] GetUserRoles(string email) {
            return base.Channel.GetUserRoles(email);
        }
        
        public System.Threading.Tasks.Task<Commonlayer.Role[]> GetUserRolesAsync(string email) {
            return base.Channel.GetUserRolesAsync(email);
        }
        
        public Commonlayer.Views.RolesView[] GetUserRolesV(string email) {
            return base.Channel.GetUserRolesV(email);
        }
        
        public System.Threading.Tasks.Task<Commonlayer.Views.RolesView[]> GetUserRolesVAsync(string email) {
            return base.Channel.GetUserRolesVAsync(email);
        }
        
        public void AddCreditCard(string email, string creditcardt, string cvv, string holder, decimal number) {
            base.Channel.AddCreditCard(email, creditcardt, cvv, holder, number);
        }
        
        public System.Threading.Tasks.Task AddCreditCardAsync(string email, string creditcardt, string cvv, string holder, decimal number) {
            return base.Channel.AddCreditCardAsync(email, creditcardt, cvv, holder, number);
        }
        
        public string GetPrivateKey(string email) {
            return base.Channel.GetPrivateKey(email);
        }
        
        public System.Threading.Tasks.Task<string> GetPrivateKeyAsync(string email) {
            return base.Channel.GetPrivateKeyAsync(email);
        }
    }
}
