//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commonlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colour
    {
        public Colour()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ColourID { get; set; }
        public string Colour1 { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
