//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commonlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public CreditCard()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public string CardType { get; set; }
        public decimal CardNumber { get; set; }
        public string CardOwner { get; set; }
        public string CVV { get; set; }
        public string Username { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
