//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commonlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public CreditCard()
        {
            this.Users = new HashSet<User>();
        }
    
        public int CardID { get; set; }
        public string CardType { get; set; }
        public decimal CardNumber { get; set; }
        public string CardOwner { get; set; }
        public System.DateTime CardExpiryDate { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
