//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commonlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public string Date { get; set; }
        public string Username { get; set; }
        public Nullable<decimal> CardUsed { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
