//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderMarket.OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrderDetails", ReplyAction="http://tempuri.org/IOrderService/AddOrderDetailsResponse")]
        void AddOrderDetails(int orderid, int productid, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrderDetails", ReplyAction="http://tempuri.org/IOrderService/AddOrderDetailsResponse")]
        System.Threading.Tasks.Task AddOrderDetailsAsync(int orderid, int productid, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        void AddOrder(string username, decimal number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(string username, decimal number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/LastOrder", ReplyAction="http://tempuri.org/IOrderService/LastOrderResponse")]
        Commonlayer.Views.OrderView LastOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/LastOrder", ReplyAction="http://tempuri.org/IOrderService/LastOrderResponse")]
        System.Threading.Tasks.Task<Commonlayer.Views.OrderView> LastOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrder", ReplyAction="http://tempuri.org/IOrderService/GetOrderResponse")]
        Commonlayer.Views.OrderView GetOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrder", ReplyAction="http://tempuri.org/IOrderService/GetOrderResponse")]
        System.Threading.Tasks.Task<Commonlayer.Views.OrderView> GetOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrderID", ReplyAction="http://tempuri.org/IOrderService/GetOrderIDResponse")]
        int GetOrderID(int productID, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetOrderID", ReplyAction="http://tempuri.org/IOrderService/GetOrderIDResponse")]
        System.Threading.Tasks.Task<int> GetOrderIDAsync(int productID, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : TraderMarket.OrderService.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<TraderMarket.OrderService.IOrderService>, TraderMarket.OrderService.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddOrderDetails(int orderid, int productid, int quantity) {
            base.Channel.AddOrderDetails(orderid, productid, quantity);
        }
        
        public System.Threading.Tasks.Task AddOrderDetailsAsync(int orderid, int productid, int quantity) {
            return base.Channel.AddOrderDetailsAsync(orderid, productid, quantity);
        }
        
        public void AddOrder(string username, decimal number) {
            base.Channel.AddOrder(username, number);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(string username, decimal number) {
            return base.Channel.AddOrderAsync(username, number);
        }
        
        public Commonlayer.Views.OrderView LastOrder() {
            return base.Channel.LastOrder();
        }
        
        public System.Threading.Tasks.Task<Commonlayer.Views.OrderView> LastOrderAsync() {
            return base.Channel.LastOrderAsync();
        }
        
        public Commonlayer.Views.OrderView GetOrder(int id) {
            return base.Channel.GetOrder(id);
        }
        
        public System.Threading.Tasks.Task<Commonlayer.Views.OrderView> GetOrderAsync(int id) {
            return base.Channel.GetOrderAsync(id);
        }
        
        public int GetOrderID(int productID, string username) {
            return base.Channel.GetOrderID(productID, username);
        }
        
        public System.Threading.Tasks.Task<int> GetOrderIDAsync(int productID, string username) {
            return base.Channel.GetOrderIDAsync(productID, username);
        }
    }
}
